### ISSUE TITLE
strike through 

### ISSUE THREAD

**Issue by joshp23** [aliva/gedit-markdownpreview#10]
Strike through is not rendering with Gedit 3.28.1 and latest from Master.

**Comment by aliva** [comment]
It seems that `python-markdown` doesn't support strike through which means we need to use a 3rd party extension, [link](https://github.com/facelessuser/pymdown-extensions/blob/master/pymdownx/tilde.py)

we can say if `pymdown-extensions` is already installed,  then load `strike through` (as an optional thing)

Or simply copy related files into this plugin and automatically load them. 

What do you think?

**Comment by joshp23** [comment]
sreikerhrough is common enough, so autoloading seems the best way, IMO.

**Comment by joshp23** [comment]
[this](https://github.com/facelessuser/pymdown-extensions/blob/master/pymdownx/tasklist.py) looks like a winner as well :)

**Comment by joshp23** [comment]
So I went with your original suggestion of checking for the installed `pymdown-extensions` package, and then loading the extensions for strike through and task lists. I also loaded the `extra` extension in both cases rather than loading individual extensions that are contained therein. 

I updated the readme to reflect supported syntax with links.
