### ISSUE TITLE
Not working with gedit 3.34.1

### ISSUE THREAD

**Issue by yochananmarqos** [aliva/gedit-markdownpreview#11]
I just remembered I had this plugin installed and realized it's no longer working. Nothing happens using the keyboard shortcut and there's no stdout from gedit at all. I'm not sure how to debug it. I'm using Manjaro GNOME.

```
/home/yochanan/.local/share/gedit/plugins/
├── markdownpreview
│   ├── markdownpreview.py
│   ├── style.css
│   └── template.html
├── markdownpreview.plugin
```

**Comment by yochananmarqos** [comment]
Nevermind, I realized `markdownpreview.plugin` needed to be in the markdownpreview folder.

**Comment by yochananmarqos** [comment]
Again, I completely forgot about this. Same issue, now using Gedit 3.34.1. I forgot to mention I added this to the [AUR](https://aur.archlinux.org/packages/gedit-markdownpreview-git) and have it installed in `/usr/share/gedit/plugins/`. No other working plugins have a `.plugin` file.

I don't believe it ever appeared in Preferences > Plugins to enable.

I also tried [this one](https://github.com/GeorgesStavracas/gedit-markdown) and it doesn't work, either.

**Comment by aliva** [comment]
I'm on `3.34.0` and it works fine, (I'm using debian sid), maybe you are trying the wrong path? on debian some plugins are in `/usr/lib/x86_64-linux-gnu/gedit/plugins` and they have the `.plugin` file.

maybe checking where other packages are storing their `*.plugin` file and see what happens

or maybe something changes on `3.34.1` and I should update

**Comment by yochananmarqos** [comment]
You're right, the plugins with `.plugin` files are in `/usr/lib/gedit/plugins/`. All the other plugins have their `.plugin` files in the main folder, not in their corresponding folder; yet yours has it in the corresponding folder.

Sorry to bother you, I just need to stop forgetting everything.
