### ISSUE TITLE
filetypes

### ISSUE THREAD

**Issue by hcal** [aliva/gedit-markdownpreview#6]
The plugin is great.  It seems to be driven by the file name extension.  It works when the file name ends in .mkd Could you add support for .md which I believe is another common markdown file extension.

**Comment by aliva** [comment]
Hi
Actually no, It depends on gedit internal file type detection ([link to code](https://github.com/aliva/gedit-markdownpreview/blob/master/markdownpreview.py#L84L92))

so if file is detected as markdown by gedit then plugin should work fine, (check if your file type is correctly detected)

note that you should pres `ctr+alt+m` to open preview

If it doesn't work please open gedit in terminal, open markdown file, press `ctrl-alt-m` then check if there is any error on output, also make sure plugin is active

If above didn't work we might need to do some debugging :-)

**Comment by hcal** [comment]
No, I made an assumption about what was happening with too little information.  It works as you describe.   I appreciate you making this and thanks for the help.
