### ISSUE TITLE
request: editor auto formating

### ISSUE THREAD

**Issue by hcal** [aliva/gedit-markdownpreview#8]
I was wondering if it would be possible to add a feature where the editor predicts some basic data entry needs as you type.  For example, if you're writing a bullet point list and are tabbed/indented, gedit could pre-enter the tab and the * character on the next line.  For a deeply nested list that would be a big help.

I'm still loving it as is though.  Thanks again for making the plugin.

**Comment by aliva** [comment]
Thanks for support :-), 

Sadly the requested feature is out of my GTK knowledge and might need some extra time to work on, I'll try to work on it in my free time but no promise
